<?php 
// أمراض جنس - ويب طب
$data = [["name"=>"ضعف الانتصاب - Erectile dysfunction"],
["name"=>"نزيف ما بعد ممارسة الجنس - Postcoital bleeding"],
["name"=>"عسر الجماع - Dyspareunia"],
["name"=>"البلوغ المبكر - Precocious puberty"],
["name"=>"مرض الايدز - Aids"],
["name"=>"انقطاع الدورة الشهرية - Menopause"],
["name"=>"مرض الزهري - Syphilis"],
["name"=>"وسائل منع الحمل - Contraception"],
["name"=>"فيروس الورم الحليمي البشري - Human Papillomavirus HPV"],
["name"=>"الامراض المنقولة جنسيًا - Sexually transmitted disease"],
["name"=>"فيروس HPV (الورم الحليمي) - HPV infection"],
["name"=>"السيلان - Gonorrhea"],
["name"=>"الزهري الخلقي - Congenital syphilis"],
["name"=>"عيوب خلقية في الجهاز التناسلي - Congenital anomalies - Mulerian system"],
["name"=>"المشعرات المهبلية - Trichmonas"],
["name"=>"انحناء القضيب - Penile curvature"],
["name"=>"الميورة الحالة لليوريا - Ureoplasma urealyticum"],
["name"=>"التثدي عند الرجال - Gynecomastia"],
["name"=>"قصور الغدد التناسلية - Hypogonadism"],
["name"=>"سرعة القذف - Premature Ejaculation"],
["name"=>"الاضطرابات الجنسية - Sexual Dysfunction"],
["name"=>"الاضطراب الجنسي لدى النساء - Female Sexual Dysfunction"],
["name"=>"الانحراف الجنسي - Paraphilia"],
["name"=>"عشق الاطفال - Pedophilia"],
["name"=>"الامراض المنقولة بالجنس الشرجي - Anal sexually transmitted diseases"],
["name"=>"ورم لقمي مسطح - Condyloma lata"],
["name"=>"الورم الحبيبي اللمفي المنقول جنسيًا - Lymphogranuloma venereum"],
["name"=>"الفطريات المهبلية - Vaginal Yeast Infection"]];