<?php 
// أمراض العيون - ويب طب
$data = [["name"=>"قصر النظر - Myopia"],
["name"=>"التهاب الشبكية الصباغي - Retinitis pigmentosa - RP"],
["name"=>"اعتلال الشبكية السكري - Diabetic retinopathy"],
["name"=>"متلازمة تولوزا هنت - Tolosa Hunt syndrome"],
["name"=>"متلازمة بارديت - بيدل - Bardet - Biedl syndrome"],
["name"=>"مرض الساد - Cataract"],
["name"=>"شعيرة العين - Stye"],
["name"=>"الزرق - Glaucoma"],
["name"=>"مرض عمى الالوان - Color Blindness"],
["name"=>"اعتلال كلية السكري - Diabetic nephropathy"],
["name"=>"حول - Strabismus"],
["name"=>"كسل العين - Amblyopia"],
["name"=>"مرض التنكس البقعي - Age-related Macular Degeneration"],
["name"=>"التراخوما - Trachoma"],
["name"=>"التهاب العنبية - Uveitis"],
["name"=>"التهاب الملتحمة - Conjuctivitis -Pink Eye"],
["name"=>"تشنج الجفن - Blepharospasm"],
["name"=>"جفاف العيون - Dry Eyes"],
["name"=>"التهاب العين - Eye Infections"],
["name"=>"جفاف العين - Xerophtalmia- dry eyes"],
["name"=>"التهاب باطن المقلة - Endophthalmitis"],
["name"=>"الزرق الخلقي الاولي - Primary congenital glaucoma"],
["name"=>"الزرق مفتوح الزاوية - Open angle glaucoma"],
["name"=>"الزرق متضيق الزاوية - Closed angle glaucoma"],
["name"=>"الزجاجي المنفصل - (PVD) Posterior Vitreous Detachment"],
["name"=>"الضمور البصري - Optic atrophy"],
["name"=>"سد شريان الشبكية - Retinal artery occlusion"],
["name"=>"التهاب الجفون - Blepharitis"],
["name"=>"التهاب بكتيري بالقرنية - Bacterial keratitis Cornea"],
["name"=>"وذمة حليمة العصب البصري - Swollen disc Papilledema"],
["name"=>"الورم الارومي الشبكي - Retinoblastoma"],
["name"=>"فقر الدم المرافق لخلل تكون الكريات الحمر الخلقي - Congenital dyserythropoietic anemia"]];