<?php 
// أمراض الريجيم وتخفيف الوزن - ويب طب
$data = [["name"=>"حساسية الحليب - Milk allergy"],
["name"=>"الارتجاع المعدي المريئي - Gastroesophangeal reflux disorder"],
["name"=>"السمنة - Obesity"],
["name"=>"فقدان الوزن غير المبرر - Unexplained weight loss"],
["name"=>"القهم العصابي - Anorexia nervosa"],
["name"=>"الدنف - Cachexia"],
["name"=>"فقد البروتين الشحمي بيتا من الدم - Abetalipoproteinemia"],
["name"=>"السمنة لدى الاطفال - Obesity in childhood"],
["name"=>"اضطرابات استقلاب الاحماض الامينية - Disorders of amino acid metabolism"],
["name"=>"امراض الاحماض العضوية - Organic acid diseases"],
["name"=>"اضطرابات اكسدة الاحماض الدهنية - Fatty-acids beta-oxidation disorders"],
["name"=>"فغر المعدة - Gastrostomy"],
["name"=>"متلازمة الامعاء القصيرة - Short bowel syndrome"],
["name"=>"البومين - Albumin"],
["name"=>"السمنة المرضية - Morbid obesity"],
["name"=>"فرط الحساسية الغذائية - Food Hypersensitivity"],
["name"=>"كواشيوركور - Kwashiorkor"],
["name"=>"سوء الامتصاص - Malabsorption"],
["name"=>"سوء التغذية - Malnutrition"],
["name"=>"حساسية الغذاء - Food allergy"],
["name"=>"نقص البومين الدم - Hypoalbuminemia"],
["name"=>"امراض تسببها المجاعة - Diseases caused by starvation"]];