<?php 
// أمراض السكري - ويب طب
$data = [["name"=>"التهاب البنكرياس - Pancreatitis"],
["name"=>"قرحة الكرب - Stress ulcer"],
["name"=>"التهاب البنكرياس الحاد - Pancreatitis"],
["name"=>"مرض السكري - Diabetes"],
["name"=>"اعتلال كلية السكري - Diabetic nephropathy"],
["name"=>"قصور البنكرياس - Pancreatic Insufficiency"],
["name"=>"قرحة الضغط - Pressure Sore"],
["name"=>"بيلة بروتينية - Proteinuria"],
["name"=>"نقص سكر الدم - Hypoglycemia"],
["name"=>"نقص سكر الدم الحاد - Hypoglycemia"],
["name"=>"ورم انسوليني - Insulinoma"],
["name"=>"تقرح الرجل - Leg ulcer"],
["name"=>"حساسية الانسولين - Insulin allergy"],
["name"=>"فرط سكر الدم - Hyperglycemia"],
["name"=>"ضعف تحمل الغلوكوز - Impaired Glucose Tolerance - IGT"],
["name"=>"خلل في الجلوكوز بالصوم - Impaired Fasting Glucose"],
["name"=>"فرط شحميات الدم لدى مرضى السكري - Hyperlipidemia in diabetes"],
["name"=>"الحماض الكيتوني السكري - Diabetic Ketoacidosis"],
["name"=>"تصلب الشرايين لدى مرضى السكري - Atherosclerosis in diabetes"],
["name"=>"السكري الذاتية للبالغين - Latent Autoimmune Diabetes of the Adult - LADA"],
["name"=>"السكري الحملي - Gestational diabetes"],
["name"=>"سكري الشبان الناضجين - Maturity Onset Diabetes of the Young - MODY"],
["name"=>"سكري من النوع الثاني - Type 2 diabetes"],
["name"=>"سكري من النوع الاول - Type 1 Diabetes"],
["name"=>"السكري الناتج عن حالات خاصة - Other types of diabetes"],
["name"=>"الحساسية للانسولين - Insulin sensitivity"],
["name"=>"اعتلال الشبكية السكري - Diabetic retinopathy"],
["name"=>"سمية الغلوكوز - Glucose toxicity"],
["name"=>"سمية الدهون - Lipotoxicity"],
["name"=>"مقاومة الانسولين - Insulin resistance"],
["name"=>"متلازمة الايض - Metabolic syndrome"],
["name"=>"قصور البنكرياس لدى الاطفال - Pancreatic insufficiency children"],
["name"=>"نقص سكر الدم لدى الرضع - Hypoglycemia in a Newborn Baby"]];